// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/GianGoulart/CrudProdutos/model"
	mock "github.com/stretchr/testify/mock"
)

// IProdutoApp is an autogenerated mock type for the IProdutoApp type
type IProdutoApp struct {
	mock.Mock
}

// CreateProduto provides a mock function with given fields: ctx, _a1
func (_m *IProdutoApp) CreateProduto(ctx context.Context, _a1 *model.Produto) (*model.Produto, error) {
	ret := _m.Called(ctx, _a1)

	var r0 *model.Produto
	if rf, ok := ret.Get(0).(func(context.Context, *model.Produto) *model.Produto); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Produto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.Produto) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProduto provides a mock function with given fields: ctx, codigo
func (_m *IProdutoApp) DeleteProduto(ctx context.Context, codigo string) (*model.Produto, error) {
	ret := _m.Called(ctx, codigo)

	var r0 *model.Produto
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Produto); ok {
		r0 = rf(ctx, codigo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Produto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, codigo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProdutoByCodigo provides a mock function with given fields: ctx, codigo
func (_m *IProdutoApp) GetProdutoByCodigo(ctx context.Context, codigo string) (*model.Produto, error) {
	ret := _m.Called(ctx, codigo)

	var r0 *model.Produto
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Produto); ok {
		r0 = rf(ctx, codigo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Produto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, codigo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProdutoByNome provides a mock function with given fields: ctx, nome
func (_m *IProdutoApp) GetProdutoByNome(ctx context.Context, nome string) (*[]model.Produto, error) {
	ret := _m.Called(ctx, nome)

	var r0 *[]model.Produto
	if rf, ok := ret.Get(0).(func(context.Context, string) *[]model.Produto); ok {
		r0 = rf(ctx, nome)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.Produto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nome)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProdutos provides a mock function with given fields: ctx
func (_m *IProdutoApp) GetProdutos(ctx context.Context) (*[]model.Produto, error) {
	ret := _m.Called(ctx)

	var r0 *[]model.Produto
	if rf, ok := ret.Get(0).(func(context.Context) *[]model.Produto); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.Produto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduto provides a mock function with given fields: ctx, _a1
func (_m *IProdutoApp) UpdateProduto(ctx context.Context, _a1 *model.Produto) (*model.Produto, error) {
	ret := _m.Called(ctx, _a1)

	var r0 *model.Produto
	if rf, ok := ret.Get(0).(func(context.Context, *model.Produto) *model.Produto); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Produto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.Produto) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
